apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-jvm-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/croway/developer-charts
    targetRevision: HEAD
    path: quarkus-pipeline
    helm:
      values: |
        domain: croway
        system: quarkus
        component: quarkus-jvm
        deployment: jvm
  destination:
    server: https://kubernetes.default.svc
    namespace: quarkus-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
